theme: jekyll-theme-cayman
title: "Linux Help Docs"
description: "Сборник инструкций и шпаргалок по Linux"
plugins:
  - jekyll-last-modified-at

nav:
  - name: "📑 Содержание"
    link: "/"
  - name: "⏰ Время"
    children:
      - name: "Настройка NTP"
        link: "/01_ntp"
      - name: "Временные метки"
        link: "/07_file_timestamps"
  - name: "📂 Файлы"
    children:
      - name: "Версионный бэкап (cp, cron, rsync)"
        link: "/02_cp_cron_rsync"
      - name: "Копирование расширенно"
        link: "/03_copy_advanced"
      - name: "Архивы"
        link: "/04_archives"
      - name: "Архивы - расширенно"
        link: "/18_archives"        
      - name: "Операции с файлами"
        link: "/13_file_operation" 
      - name: "Операции с директориями"
        link: "/14_dir_operation"      
      - name: "Поиск и просмотр файлов"
        link: "/15_find_file"                
  - name: "📊 Мониторинг"
    children:
      - name: "Мониторинг Linux"
        link: "/05_monitoring"
      - name: "Информация о системе"
        link: "/06_sysinfo"
  - name: "👤 Пользователи"
    children:
      - name: "Пользователи и группы"
        link: "/08_users"
      - name: "Права доступа"
        link: "/12_permissions"
  - name: "🌐 Сети"
    children:
      - name: "Кратко"
        link: "/10_network_basics"
      - name: "Подробнее"
        link: "/11_network_details"
      - name: "Настройка Бонда"
        link: "/16_Bonding"
      - name: "Статичные интерфейсы"
        link: "/17_inet_static"        
  - name: "⚙️ Shell"
    children:
      - name: "История команд"
        link: "/09_shell_history"
